### ISSUE TITLE
haywire_hello_world crashes under benchmark testing in Ubuntu 13.10

### ISSUE THREAD

**Issue by boa86** [kellabyte/Haywire#37]
Just cloned code from github, run build.sh
After building, start haywire_hello_world debug version
And run  ab -n 200000 -c 132 http://localhost:8000/

haywire_hello_world always craches after completed 45k requests 

root@lab199:~/work/nm_cpp/Haywire/builds/unix/debug# ./haywire_hello_world
Added route /stats
Added route /
Listening on 0.0.0.0:8000
haywire_hello_world: lib/libuv/src/unix/stream.c:996: uv__read: Assertion `buf.base != ((void *)0)' failed.
haywire_hello_world: lib/libuv/src/unix/stream.c:996: uv__read: Assertion `buf.base != ((void *)0)' failed.
Aborted (core dumped)

**Comment by kellabyte** [comment]
This should be fixed now.
