### ISSUE TITLE
Build Failing on Windows (x64, Windows 10, VS 2015)

### ISSUE THREAD

**Issue by mikeptweet** [kellabyte/Haywire#76]
"C:\Haywire\haywire.sln" (default target) (1) ->
"C:\Haywire\haywire_hello_world.vcxproj.metaproj" (default target) (4) ->
"C:\Haywire\haywire_hello_world.vcxproj" (default target) (7) ->
(Link target) ->
  program.obj : error LNK2019: unresolved external symbol opt_config_init refer
enced in function main [C:\Haywire\haywire_hello_world.vcxproj]
  program.obj : error LNK2019: unresolved external symbol opt_config_free refer
enced in function main [C:\Haywire\haywire_hello_world.vcxproj]
  program.obj : error LNK2019: unresolved external symbol opt_args_free referen
ced in function main [C:\Haywire\haywire_hello_world.vcxproj]
  program.obj : error LNK2019: unresolved external symbol opt_config_parse refe
renced in function main [C:\Haywire\haywire_hello_world.vcxproj]
  program.obj : error LNK2019: unresolved external symbol opt_flag_bool referen
ced in function main [C:\Haywire\haywire_hello_world.vcxproj]
  program.obj : error LNK2019: unresolved external symbol opt_flag_int referenc
ed in function main [C:\Haywire\haywire_hello_world.vcxproj]
  program.obj : error LNK2019: unresolved external symbol opt_flag_string refer
enced in function main [C:\Haywire\haywire_hello_world.vcxproj]
  C:\Haywire\builds\windows\debug\haywire_hello_world\haywire_hello_world.exe :
 fatal error LNK1120: 7 unresolved externals [C:\Haywire\haywire_hello_world.vc
xproj]

    134 Warning(s)
    8 Error(s)

**Comment by nmdguerreiro** [comment]
It looks like the hello world source set doesn't include opt.c. I don't
have access to any Windows machines to confirm though.

**Comment by mikeptweet** [comment]
I got it compiled by including opt.c in the visual studio project, however when I run the program and fire off a request, it immediately exits. See the attached gif.

![haywire](https://cloud.githubusercontent.com/assets/1769876/11815394/77d6c7fa-a319-11e5-883f-13d2c4df8d30.gif)

**Comment by nmdguerreiro** [comment]
If you compile in debug mode, do you get an error message when you run it?

**Comment by mikeptweet** [comment]
Nope ... nothing. The same thing happens if I try to connect via the
browser. The server ends immediately.

**Comment by nmdguerreiro** [comment]
I wonder what
https://github.com/kellabyte/Haywire/blob/master/src/haywire/http_server.c#L203
is
actually returning in that case. Could you print the result of that call?

**Comment by mikeptweet** [comment]
I set up the debugger in Visual Studio and it breaks here (strlen.asm)

[image: Inline image 1]

**Comment by mikeptweet** [comment]
Here is where the error occurs ... getting the strlen(current_time)

[image: Inline image 1]

**Comment by mikeptweet** [comment]
Sorry ... here's the screenshot

![error](https://cloud.githubusercontent.com/assets/1769876/11839265/5e1b0eba-a3ba-11e5-8470-0ec4363a6dd9.JPG)

**Comment by nmdguerreiro** [comment]
Humm, that's weird. I just checked the ![documentation on MSDN](https://msdn.microsoft.com/en-us/library/59w5xcdy.aspx) and `ctime` is supposed to return a null terminated string, so strlen shouldn't have an issue.

Note that `current_datetime.length` is initialized until the next line runs. Does strlen cause a segmentation fault or does it return?

**Comment by mikeptweet** [comment]
It causes a segmentation fault and the program exits

**Comment by nmdguerreiro** [comment]
And what's the value of `current_time` btw?

**Comment by mikeptweet** [comment]
Error Reading Character Of Strings
Unable to read memory

**Comment by mikeptweet** [comment]
If you need a Windows Environment to test on ... just load up this Hands On Lab from Microsoft and it gives you a full blown remote Windows - Visual Studio 2015 environment all avilable from a web browser 

https://vlabs.holsystems.com/vlabs/technet?eng=VLabs&auth=none&src=vlabs&altadd=true&labid=21201&lod=true

**Comment by nmdguerreiro** [comment]
Sweet!

**Comment by nmdguerreiro** [comment]
@mikeptweet - I ran `build.bat` to generate the solution files and I didn't have to add any additional sources. After that I was able to reproduce the error. I fixed it by adding:

```c
#include <time.h>
```

at the top of http_response_cache.c.

Can you try doing that and running again just to confirm?

**Comment by nmdguerreiro** [comment]
Opened #77 to fix it. Without the header, the current time is returns as negative and that causes ctime to return an invalid string.

**Comment by mikeptweet** [comment]
Bingo ... thanks a bunch :-)

**Comment by nmdguerreiro** [comment]
Happy to help :-)
