### ISSUE TITLE
Ragel parser

### ISSUE THREAD

**Issue by perplexes** [kellabyte/Haywire#84]
Did y'all give thought to using mongrel's http parser written in Ragel? Or using Ragel to make your own? Wonder how it would affect the benchmarks/correctness...

**Comment by kellabyte** [comment]
Is there any proof that parser can do near 10,000,000 requests/second? Haywire has 2 parsers available (soon). A SSE4 hardware accelerated one and one for platforms not supporting SSE4.

**Comment by perplexes** [comment]
None that I can find.

I seem to remember that its focus was on correctness and preventing attacks on the surface of HTTP. It would be interesting to benchmark alongside (and also fuzz-test and try to break, etc).

Just wanted to float the idea - thanks.
